name: Gold Features

sidebar:
  # background: linear-gradient(0deg, rgb(201,38,83) 0%, rgb(252,48,104) 80%)
  background: black

# match: ['modal.md'],,

order:
  - +Intro

excludeDir:
  - node_modules
  - ./docs

assets:
  - docsHelper/lib/require.js
  - docsHelper/lib/base.js
  - docsHelper/featurify.js
  - modal/lib
  - icons/lib
  - icons/docs/icons.svg
  - icons/docs/icons.json
  - object-fit/lib
  - object-fit/docs/files
  - slider/lib
  - slider/docs/files
  - accordion/lib
  - form/lib
  - form/docs/files
  - gallery/lib
  - gallery/docs/files
  - map/lib
  - map/assets/features/map
  - touch-hover/lib
  - cookie-disclaimer/lib
  - headroom/lib
  - page-transition/lib
  - masonry/lib
headHtml: >
  <link rel="stylesheet" type="text/css" href="modal/lib/style.css">
  <link rel="stylesheet" type="text/css" href="icons/lib/style.css">
  <link rel="stylesheet" type="text/css" href="object-fit/lib/style.css">
  <link rel="stylesheet" type="text/css" href="slider/lib/style.css">
  <link rel="stylesheet" type="text/css" href="accordion/lib/style.css">
  <link rel="stylesheet" type="text/css" href="form/lib/style.css">
  <link rel="stylesheet" type="text/css" href="gallery/lib/style.css">
  <link rel="stylesheet" type="text/css" href="map/lib/style.css">
  <link rel="stylesheet" type="text/css" href="touch-hover/lib/style.css">
  <link rel="stylesheet" type="text/css" href="cookie-disclaimer/lib/style.css">
  <link rel="stylesheet" type="text/css" href="page-transition/lib/style.css">
  <script src="docsHelper/lib/require.js"></script>
  <script src="docsHelper/lib/base.js"></script>
  <script src="docsHelper/featurify.js"></script>
