name: Gold Features

theme:
  sidebar:
    background: black

# match: ['modal.md'],,

order:
  - +Intro

excludeDir:
  - node_modules
  - ./docs

examples:
  js:
    - docsHelper/lib/intersection-observer.js
    - docsHelper/lib/require.js
    - docsHelper/lib/base.js
    - docsHelper/featurify.js
  css:
    - packages/modal/lib/style.css
    - packages/icons/lib/style.css
    - packages/object-fit/lib/style.css
    - packages/slider/lib/style.css
    - packages/accordion/lib/style.css
    - packages/form/lib/style.css
    - packages/gallery/lib/style.css
    - packages/map/lib/style.css
    - packages/touch-hover/lib/style.css
    - packages/cookie-disclaimer/lib/style.css
    - packages/page-transition/lib/style.css
    - packages/masonry/lib/style.css
    - packages/reveal-trigger/lib/style.css
    - packages/element-loader/lib/style.css

assets:
  - packages/modal/lib
  - packages/icons/lib
  - packages/icons/docs/icons.svg
  - packages/icons/docs/icons.json
  - packages/object-fit/lib
  - packages/object-fit/docs/files
  - packages/overflow-detector/lib
  - packages/slider/lib
  - packages/slider/docs/files
  - packages/accordion/lib
  - packages/accordion/assets/features/accordion
  - packages/dom-state-handler/lib
  - packages/dom-state-handler/docs/files
  - packages/form/lib
  - packages/form/docs/files
  - packages/gallery/lib
  - packages/gallery/docs/files
  - packages/gallery/assets/features/gallery
  - packages/map/lib
  - packages/map/assets/features/map
  - packages/touch-hover/lib
  - packages/cookie-disclaimer/lib
  - packages/headroom/lib
  - packages/page-transition/lib
  - packages/masonry/lib
  - packages/reveal-trigger/lib
  - packages/reveal-trigger/docs/files
  - packages/element-loader/lib
  - packages/element-loader/docs/files
  - packages/vh-offset/lib

